# Generated by Django 4.1.4 on 2023-05-05 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='hotel',
        ),
        migrations.AddField(
            model_name='rooms',
            name='hotel_connected',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='Hotel.hotels'),
        ),
    ]
