# Generated by Django 4.1.4 on 2023-05-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0004_booking_roomtype_delete_reservation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_type',
            field=models.CharField(choices=[('1', 'deluxe'), ('2', 'premium')], max_length=15),
        ),
    ]
