# Generated by Django 4.1.4 on 2023-05-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0007_booking_roomtype_delete_reservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
