# Generated by Django 4.1.4 on 2023-05-05 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0008_roomtype_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='roomnumber',
            new_name='number',
        ),
    ]
