# Generated by Django 4.1.4 on 2023-05-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0009_rename_roomnumber_rooms_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='guest_name',
            new_name='guest',
        ),
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
